version: "3.7"
services:
  # Laravel Service
  fpm-service:
    container_name: fpm-service
    restart: always
    tty: true
    working_dir: /var/www/app
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/app
    networks:
      - product-listing-network

  # Nginx Service
  app-server:
    image: nginx:alpine
    container_name: app-server
    restart: always
    tty: true
    ports:
      - 8100:8080
    volumes:
      - .:/var/www/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - fpm-service
    networks:
      - product-listing-network

# Docker Networks
networks:
  product-listing-network:
    driver: bridge
