version: "3.7"
services:
  # Laravel Service
  application:
    container_name: product-listing
    restart: always
    tty: true
    working_dir: /var/www/app
    build:
      context: .
      dockerfile: docker/Dockerfile
    #    ports:
    #      - 9001:9000
    #      - 9002:9001
    volumes:
      - .:/var/www/app
    networks:
      - product-listing-network

  # Nginx Service
  server:
    image: nginx:alpine
    container_name: server
    restart: always
    tty: true
    ports:
      - 8100:8080
    volumes:
      - .:/var/www/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - application
    networks:
      - product-listing-network

# Docker Networks
networks:
  product-listing-network:
    driver: bridge
